### ISSUE TITLE
Question regarding pings

### ISSUE THREAD

**Issue by runjak** [zoupio/spec#2]
Hey :wave:

looking at the [spec section on ping](https://github.com/zoupio/spec/blob/main/spec.md#ping) I've been wondering:
should the HTTP method be restricted to something like POST here, or is it intentional that no method is mentioned?

What are the desired methods that a server should support for ping endpoints?

**Comment by yetzt** [comment]
also a good point. i think it should be restricted to `POST` to prevent some shenanigans.

**Comment by runjak** [comment]
Agreed - I think `GET` could enable some issues, and POST seems to make more sense than `PATCH`, `PUT` and others.

**Comment by runjak** [comment]
Took the liberty to create a PR: #5 - closing this issue in favor of it :).

**Comment by yetzt** [comment]
thank you, merged.
