### ISSUE TITLE
Question regarding authors

### ISSUE THREAD

**Issue by runjak** [zoupio/spec#3]
Hey :wave:

looking at the [spec section for authors](https://github.com/zoupio/spec/blob/main/spec.md#authors) I've noted that  it reads `posts must contain one author object, which`.

If I'm not mistaken, [www.jsonfeed.org/version/1.1/](https://www.jsonfeed.org/version/1.1/#items-a-name-items-a) defines an author as having at least one of the fields `name`, `url` and `avatar`. Are the expected constraints here the same, or should an author always have a `name`, `url` and `avatar`?

**Comment by yetzt** [comment]
good point. ideally `name`, `url` and `avatar` should all be present (avatar could be replaced by a generic default avatar if none specified). but, having only one of them shouldn't break things, as ground work to at some point follow/import generic jsonfeeds (as soup did with rss/atom).
