### ISSUE TITLE
Is it valid to not have a next_feed in feed.json?

### ISSUE THREAD

**Issue by runjak** [zoupio/spec#4]
Looking at [spec.md#feed](https://github.com/zoupio/spec/blob/main/spec.md#feed) I noticed that it states:
`next_url must contain the next batches feed url`.

However https://www.jsonfeed.org/version/1.1/ appears to state that the `next_url` field is optional.
Would I be correct to assume that it is valid to omit the `next_url` if there are no additional entries?

If `next_url` cannot be omitted: how does software recognize that the end of a feed is reached?

I imagine that depending on the implementation it would be possible to have some intermittent batches in a feed that don't have any items in them. For example an implementation that batches items on a 24h basis could have nothing for a day?

**Comment by yetzt** [comment]
yes. the wording is poor there, if the feed reached the end `next_url` must not be present. thanks for pointing it out. changed it in 389e147e

**Comment by runjak** [comment]
Thanks for taking care 🙏
It may be that I'm currently fiddling with some kind of prototype - hence all the fuzz.
If I can remain focused long enough to get something that works at least a bit I'd be happy to share :)

**Comment by yetzt** [comment]
i'll take a look at it. maybe i can share my (mostly ux-focussed) prototype if i find the time to clean it up.
